server:
  port: 8888
spring:
  application:
    name: pagatu-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_PATH:file:../config-repo,file:./config-repo,file:///C:/Users/USUARIO/Documents/Tarea Eureka/config-repo}
